# Generated by Django 5.0 on 2023-12-22 06:56

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='inv_id',
            field=models.IntegerField(default=builtins.id, unique=True),
        ),
    ]
