# Generated by Django 5.0 on 2023-12-22 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_inv_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='inv',
            field=models.ForeignKey(default=1045, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice', to_field='inv_id'),
        ),
    ]
