# Generated by Django 5.0 on 2023-12-22 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoicedetails_inv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='inv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice', to_field='inv_id'),
        ),
    ]
