# Generated by Django 5.0 on 2023-12-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoice_inv_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedetails',
            old_name='inv',
            new_name='inv_id',
        ),
    ]
