# Generated by Django 5.0 on 2023-12-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_rename_inv_invoicedetails_inv_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedetails',
            old_name='inv_id',
            new_name='inv',
        ),
    ]
