# Generated by Django 5.0 on 2023-12-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_rename_inv_invoicedetails_inv_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
