# Generated by Django 5.0 on 2023-12-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_invoicedetails_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='inv_id',
            field=models.BigIntegerField(default=3930, unique=True),
        ),
    ]
